export const dogBreeds = [
    "Afghan Hound",
    "Aspin",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bernese Mountain Dog",
    "Boston Terrier",
    "Border Collie",
    "Boxer",
    "Brittany Spaniel",
    "Bulldog",
    "Dachshund",
    "Doberman Pinscher",
    "English Springer Spaniel",
    "German Shepherd",
    "German Shorthaired Pointer",
    "Golden Retriever",
    "Great Dane",
    "Havanese",
    "Labrador Retriever",
    "Mastiff",
    "Pembroke Welsh Corgi",
    "Pomeranian",
    "Poodle",
    "Rottweiler",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Weimaraner",
    "Yorkshire Terrier",
  ];
  
  export const catBreeds = [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Asian Semi-longhair",
    "Australian Mist",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "California Spangled",
    "Chartreux",
    "Chausie",
    "Cheetoh",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Donskoy",
    "Egyptian Mau",
    "Elf cat",
    "Exotic Shorthair",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian",
    "Pixie-bob",
    "Philippine Shorthair (Puspin)",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Turkish Angora",
    "Turkish Van",
  ];
  